### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by joeblew99** [nubank/nuvigator#15]
Does this support Flutter web as well as mobile ?

**Comment by leoiacovini** [comment]
Hi @joeblew99, thanks for your question!

The package does not relly in any specific mobile plugin, apart from the Flutter framework itself. We have not tested it in the web environment, just in mobile and desktop, and both works great.

I would expect it to also work in the web :). I encourage you to try it, and if anything goes wrong, feel free to file a new issue.
