### ISSUE TITLE
Generated .g.dart file doesn't import flutter/widgets

### ISSUE THREAD

**Issue by comigor** [nubank/nuvigator#16]
So, I've created a simple Router (with no NuRoutes for now) and, when the .g.dart file was generated, a build error occured ("Undefined class 'BuildContext'").

Doing some research, it seems we can't have imports on "part of" files, but that wasn't clear.
Maybe we could add a `import 'package:flutter/widgets.dart';` import requirement on README?

I'll open a PR.

For reference:
<details><summary><b>navigation.dart</b></summary>
<code>
import 'package:nuvigator/nuvigator.dart';

part 'navigation.g.dart';

@NuRouter()
class TestRouter extends BaseRouter {
  @override
  String get deepLinkPrefix => 'test/';

  @override
  Map<RouteDef, ScreenRouteBuilder> get screensMap =>
      _$testScreensMap(this);
}
</code>
</details>

<details><summary><b>navigation.g.dart</b></summary>
<code>
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'navigation.dart';

// **************************************************************************
// NuvigatorGenerator
// **************************************************************************

class TestRoutes {}

class TestNavigation {
  TestNavigation(this.nuvigator);

  final NuvigatorState nuvigator;

  static TestNavigation of(BuildContext context) =>
      TestNavigation(Nuvigator.of(context));
}

Map<RouteDef, ScreenRouteBuilder> _$testScreensMap(
    SplitTransactionRouter router) {
  return {};
}

</code>
</details>

**Comment by leoiacovini** [comment]
Yep, that's right, we need to manually require it. Thanks for the report and PR!
