### ISSUE TITLE
Separate builder and runtime into two different packages

### ISSUE THREAD

**Issue by leoiacovini** [nubank/nuvigator#21]
We should follow the community convention in splitting packages that contain code generation into different sub-packages. One containing the annotation (and in this case, maybe the Runtime code), and another one just with builder/generator code.

**Comment by viniciusmelquiades** [comment]
If the annotations aren't used by the runtime, maybe they should be in their own package as well

**Comment by leoiacovini** [comment]
No more relevant given the NEXT API revamp
