### ISSUE TITLE
Documentation update and new instructions

### ISSUE THREAD

**Issue by shrpereira** [nubank/nuvigator#24]
I'm trying to follow the documentation in order to make an example project with Nuvigator and I've found two problems with that:
- The documentation examples suggests that we use a `GlobalRouter` instance as the top level Router but looks like this class was removed in version `0.3.0`.
- Since the generated code is using Extensions, I had to do some research to find out that I'd needed to create a new file in the root directory with the name `analysis_options.yaml` and the following content to make it to work:
```
enable-experiment:
  - extension-methods
```

What about updating the docs with those details?

**Comment by leoiacovini** [comment]
Closing due to changes in the API and new documentation has been made
