### ISSUE TITLE
Add popUntil{routeName} generated method

### ISSUE THREAD

**Issue by afucher** [nubank/nuvigator#59]
Hi,

Nuvigator has some generated methods that helps a lot, I would like to add a new one `popUntil{routeName}`. It will call the `popUntil` with the predicate checking the name of the route.

I can try to implement this, if you think that this feature will be nice.

**Comment by leoiacovini** [comment]
Hey @afucher! Thanks for the issue

We have been working on a new API for Nuvigator that emphasizes DeepLink navigation, and dynamic route registering, you can find more about this here: https://github.com/nubank/nuvigator/pull/58
One of the implications of such changes is that the auto-generated navigation methods are not going to be supported anymore 😞 . This was a tradeoff we took into consideration when making the changes to the new API, and supporting the navigation methods generation would imply limiting the dynamic potential of the new API. 

Given this, I am not sure if it's worth to implement a new method of those, given the planned deprecation of this API.
We are open to feedback about the new API, and in the PR I linked you can find the Documentation of the new API.
