### ISSUE TITLE
Support to Null Safety and Flutter 2.0

### ISSUE THREAD

**Issue by pedrohsampaioo** [nubank/nuvigator#69]
The project already undergoing some type of migration to support the new features of Flutter 2.0?

**Comment by leoiacovini** [comment]
Hi @pedrohsampaioo 

Right now we are working on doing final tests and wrapping up the Next API 1.0 release (check in the `next` branch about this). Probably after that, we are going to work into the Null Safety features, but I cannot give you any timeline right now.  However, I will keep this issue open, and put any updates regarding this here, ok?

**Comment by LucasMdosAnjos** [comment]
Any update on this?

**Comment by leoiacovini** [comment]
Hello @LucasMdosAnjos 

We have decided to not support Null Safety until we remove the Legacy API. This decision was driven by the complexity to migrate both APIs to use NSBD, and the cost associated to update projects using the Legacy API. Especially given that we would be investing energy into something that is planned to be removed in the next major update.

Given this we have the following roadmap:
1. Remove the Legacy API from Nuvigator (planned for the next major release, around early-mid November)
2. Add support for Null Safety for the NEXT API (should happen right after we remove the Legacy API, given we had some spikes doing this migration already)

Sorry for the delay to implement those changes, but given the lack of bandwidth and complexities involved in doing the changes we believe this is the best decision to avoid major problems

**Comment by leoiacovini** [comment]
Sorry for the delay folks.
We have been discussing internally how to proceed with that, and I'd like to say that we are now actively working on it. The plan is divided into 2 phases:

1. Remove the Legacy API (and related deprecated code) - WIP
2. Bring support for Sound Null Safety in the NEXT API - 🔜 

Right now we are working in the PR to remove the old code, which will pave the way for the migration to happen right after it. We expect to have a `2.0.0` release with support for this in next incoming weeks if everything goes well

**Comment by leoiacovini** [comment]
PR Removing the Legacy API is already opened here: https://github.com/nubank/nuvigator/pull/101

**Comment by leoiacovini** [comment]
Support is available in the `2.0.0-beta.3` version (https://github.com/nubank/nuvigator/releases/tag/v2.0.0-beta.3). After a couple more testing, we will promote it to stable. 

Thanks for the patience and sorry for the delay from the expected timeline

**Comment by AndreiiMorais** [comment]
@leoiacovini any idea on when should be released the null safety version?
